#!/bin/bash

#This script creates a file with the of words. the script contains on each line  of words and their occurrences in the corpus. The script isalphabetically ordered.


reset (){
rm -f ~/Desktop/tg1/words_dic/words.txt
}

words(){
cat ~/Desktop/tg1/corpus_txt/* | sed -e 's/[^[:alpha:]]/ /g; /^\s*$/d'  | tr -d '\t'  | tr -s " " |tr 'A-Z' 'a-z' | tr " " "\n" | sort -d| uniq -c |sed '/1/d' | gawk '
{
   print $2 " " $1;

}' >> ~/Desktop/tg1/words_dic/words.txt
}

reset
words
